FROM python:3.11

WORKDIR /app

# คัดลอกไฟล์ที่จำเป็น
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .



# เรียกใช้ Gunicorn
CMD ["gunicorn", "main:app", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "--host=0.0.0.0", "--port=8000"]