FROM python:3.11

WORKDIR /app

# คัดลอกไฟล์ที่จำเป็น
COPY requirements.txt ./


COPY . .

# # Copy the upload folder into the container
# COPY upload /app/upload



# เรียกใช้ Gunicorn
CMD ["gunicorn", "main:app", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "--host=0.0.0.0", "--port=${PORT}"]